name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            executable: 文件批量重命名工具.exe
            artifact: windows-app
          - os: macos-latest
            platform: macos
            executable: 文件批量重命名工具.app
            artifact: macos-app

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Create app icon (Windows)
      if: matrix.platform == 'windows'
      run: python create_icon.py

    - name: Create app icon (macOS)
      if: matrix.platform == 'macos'
      run: python create_mac_icon.py

    - name: Build application (Windows)
      if: matrix.platform == 'windows'
      run: python build_windows.py

    - name: Build application (macOS)
      if: matrix.platform == 'macos'
      run: python build_macos.py

    - name: Create DMG (macOS)
      if: matrix.platform == 'macos'
      run: |
        brew install create-dmg
        python create_dmg.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: |
          dist/
          setup/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-app
        path: windows-release/

    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-app
        path: macos-release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-release/setup/*.exe
          macos-release/setup/*.dmg
          windows-release/dist/*.exe
          macos-release/dist/*.app
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 